<a href="https://colab.research.google.com/github/JonathanSosa-py/MFML/blob/main/Module1_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import numpy.linalg as nlg

### 3. Calcule los siguientes productos de matrices (si es posible).

#### A)

\begin{align}
        A = \begin{pmatrix}
        1 & 2 \\
        4 & 5 \\
        7 & 8 
        \end{pmatrix}
        B = \begin{pmatrix}
        1 & 1 & 0\\
        0 & 1 & 1\\
        1 & 0 & 1
        \end{pmatrix}
    \end{align}

In [14]:
# No es posible ya que la forma de ambas matrices es diferente.

#### B)

\begin{align}
        A = \begin{pmatrix}
        1 & 2 & 3\\
        4 & 5 & 6\\
        7 & 8 & 9
        \end{pmatrix}
        B = \begin{pmatrix}
        1 & 1 & 0\\
        0 & 1 & 1\\
        1 & 0 & 1
        \end{pmatrix}
    \end{align}

In [15]:
A = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.matrix([[1, 1, 0], [0, 1, 1], [1, 0, 1]])
AB = A.dot(B)
A, B, AB

(matrix([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]), matrix([[1, 1, 0],
         [0, 1, 1],
         [1, 0, 1]]), matrix([[ 4,  3,  5],
         [10,  9, 11],
         [16, 15, 17]]))

#### C)

\begin{align}
        A = \begin{pmatrix}
        1 & 1 & 0\\
        0 & 1 & 1\\
        1 & 0 & 1
        \end{pmatrix}
        B = \begin{pmatrix}
        1 & 2 & 3\\
        4 & 5 & 6\\
        7 & 8 & 9
        \end{pmatrix}
    \end{align}

In [16]:
AB = B.dot(A)
AB

matrix([[ 5,  7,  9],
        [11, 13, 15],
        [ 8, 10, 12]])

#### D)

\begin{align}
        A = \begin{pmatrix}
        1 & 2 & 1 & 2\\
        4 & 1 & -1 & -4\\
        \end{pmatrix}
        B = \begin{pmatrix}
        0 & 3\\
        1 & -1\\
        2 & 1\\
        5 & 2
        \end{pmatrix}
    \end{align}

In [17]:
A = np.matrix([[1, 2, 1, 2], [4, 1, -1, -4]])
B = np.matrix([[0, 3], [1, -1], [2, 1], [5, 2]])
AB = A.dot(B)
A, B, AB

(matrix([[ 1,  2,  1,  2],
         [ 4,  1, -1, -4]]), matrix([[ 0,  3],
         [ 1, -1],
         [ 2,  1],
         [ 5,  2]]), matrix([[ 14,   6],
         [-21,   2]]))

#### E)

\begin{align}
        A = \begin{pmatrix}
        0 & 3\\
        1 & -1\\
        2 & 1\\
        5 & 2
        \end{pmatrix}
        B = \begin{pmatrix}
        1 & 2 & 1 & 2\\
        4 & 1 & -1 & -4\\
        \end{pmatrix}
    \end{align}

In [19]:
AB = B.dot(A)
AB

matrix([[ 12,   3,  -3, -12],
        [ -3,   1,   2,   6],
        [  6,   5,   1,   0],
        [ 13,  12,   3,   2]])

### 7. Determine las inversas de las siguientes matrices.

#### A)

\begin{align}
        A = \begin{pmatrix}
        2 & 3 & 4\\
        3 & 4 & 5\\
        4 & 5 & 6
    \end{pmatrix}
    \end{align}




In [11]:
A = np.matrix([[2, 3, 4], [3, 4, 5], [4, 5, 6]])
Ainv = nlg.inv(A)
Ainv

LinAlgError: ignored

Since the determinant of this matrix is 0 we can say that it doesn't have a inverse matrix.

#### B)

\begin{align}
        A = \begin{pmatrix}
        1 & 0 & 1 & 0\\
        0 & 1 & 1 & 0\\
        1 & 1 & 0 & 1\\
        1 & 1 & 1 & 0
    \end{pmatrix}
    \end{align}

In [8]:
A = np.matrix([[1, 0, 1, 0], [0, 1, 1, 0], [1, 1, 0, 1], [1, 1, 1, 0]])
Ainv = nlg.inv(A)

# Demostration.
np.allclose(np.dot(A, Ainv), np.eye(4))

True